# Workflow que crea un PDF de la tesina y lo sube a GitHub Releases

name: CI
permissions:
  contents: write
on:
  # Solo se ejecuta en main cuando se crea un tag
  push:
    branches: [ "main" ]
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: github.ref_type == 'tag' # Solo se ejecuta si el commit tiene un tag
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # añadir los archivos latex del repositorio al entorno de ejecución
        uses: actions/checkout@v4
      - name: Build # buildear el PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Copy # copiar el PDF para subirlo como artefacto
        run: |
          mkdir out
          cp ./main.pdf ./out/tesina.pdf
      - uses: actions/upload-artifact@v4 # subir el PDF como artefacto
        with:
          name: tesina
          path: out/tesina.pdf
      - name: UploadToDrive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.3.1
        with: 
          target: out/tesina.pdf
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          parent_folder_id: ${{ secrets.GOOGLE_PARENT_FOLDER_ID }}
          name: ${{  github.ref_name }}.pdf
      - name: Release
        uses: softprops/action-gh-release@v2 #crear una release con el PDF
        if: github.ref_type == 'tag'
        with:
          files: out/tesina.pdf
    
